flow_start_time: "2024-07-07T00:30:00+00:00" # time travel for testing or reprocessing
                # use ISO8601 format: if UTC use +00:00 or Z

source:
  mode: local
  git:
    url: https://github.com/echostack-org/echodataflow.git
    branch: origin/main

default_work_pool_name: local
flows:
  # TESTING -- copy_raw and raw2Sv pair
  copy_raw:
    deployment_name: copy-raw
    interval: 10
    inject_time_offset: true
  raw2Sv:
    deployment_name: raw2Sv
    interval: 10
  #
  # TESTING -- create_MVBS
  create_MVBS:
    deployment_name: create-MVBS
    interval: 10
    cron_offset: 3
    inject_time_offset: true
  #
  # TESTING -- predict_hake
  predict_hake:
    deployment_name: predict-hake
    interval: 20
    inject_time_offset: true
  # copy_trawl_data:
  #   module: flows_helper
  #   deployment_name: copy-trawl-data
  #   interval: 10
  #
  # # TESTING -- USING THE SAME FLOW
  file_upload_trawl:
    deployment_name: file-upload-trawl
    flow: file_upload
    interval: 10
    cron_offset: 3
  file_upload_trawl2:
    deployment_name: file-upload-trawl2
    flow: file_upload
    interval: 10
    cron_offset: 3
  #
  # # TESTING -- TRIGGERS
  # emit_event_ABC:
  #   deployment_name: emit_event_ABC
  #   # interval: 5
  # triggered_by_event_ABC:
  #   deployment_name: triggered_by_event_ABC
  #   triggers:
  #     - expect: prefect.flow-run.Completed
  #       resource_name: emit_event_ABC
