flow_start_time: null

source:
  mode: git
  git:
    url: https://github.com/OSOceanAcoustics/echodataflow.git
    branch: main

default_work_pool_name: local
flows:
  ingest_haul:
    module: flows_biology
    deployment_name: ingest_haul
    interval: 5
    emit_events:
      - haul.ingested
  ingest_NASC:
    module: flows_integration
    deployment_name: ingest_NASC
    interval: 5
    emit_events:
      - nasc.ingested
  update_grid:
    module: flows_integration
    deployment_name: update_grid
    triggers:
      - expect: haul.ingested
        resource_name: ingest_haul
      - expect: nasc.ingested
        resource_name: ingest_NASC
  # update_cache_MVBS_lasker:
  #   module: flows_viz_cloud
  #   flow_alias: update_cache_MVBS
  #   deployment_name: update_cache_MVBS_lasker
  #   interval: 10
  #   cron_offset: 3
  #   inject_time_offset: true
  # update_cache_MVBS_dyson:
  #   module: flows_viz_cloud
  #   flow_alias: update_cache_MVBS
  #   deployment_name: update_cache_MVBS_dyson
  #   interval: 10
  #   cron_offset: 3
  #   inject_time_offset: true
